name: CI

on: [push]

jobs:


  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          username: getparanoid
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push containers
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/arm,linux/amd64,linux/arm64/v8
          tags: |
            ghcr.io/GetParanoid/db-auto-backup:latest
            getparanoid/db-auto-backup:latest
